variables:
  - &set-image-name 'IMAGE_NAME=codeberg.org/draky.dev/draky'

pipeline:

  build:
    image: docker
    environment:
      - *set-image-name
    commands:
      - apk add git make bash gettext
      - "make build VERSION=${CI_COMMIT_TAG##v} NAME=$${IMAGE_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker
    environment:
      - *set-image-name
    commands:
      - apk add make
      - docker load < ./dist/image.tar
      - "make test VERSION=${CI_COMMIT_TAG##v} NAME=$${IMAGE_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
