name: Build
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
env:
  DRAKY_IMAGE_PATH: 'dist/draky-local-build.image.tar'
  DRAKY_IMAGE_ARTIFACT_NAME: 'draky-image'
jobs:

  build:
    name: Building draky.
    runs-on: ubuntu-latest
    container:
      image: docker:24.0.2-cli-alpine3.18
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.5.3
      - name: Installing basic dependencies.
        run: apk add make
      - name: Install other dependencies.
        run: make install_build_dependencies_apk
      - name: Building.
        run: make build
      - name: Preserve image
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.DRAKY_IMAGE_ARTIFACT_NAME }}
          path: ${{ env.DRAKY_IMAGE_PATH }}
          retention-days: 1

  test-core:
    name: Testing draky-core.
    runs-on: ubuntu-latest
    container: docker:24.0.2-cli-alpine3.18
    needs: [build]
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.5.3
    - name: Installing basic dependencies.
      run: apk add make
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ env.DRAKY_IMAGE_ARTIFACT_NAME }}
        path: dist
    - name: Loading image.
      run: docker load --input $DRAKY_IMAGE_PATH
    - name: Testing core.
      run: make test-core

  test-functional:
    name: Testing functional.
    runs-on: ubuntu-latest
    container: docker:24.0.2-cli-alpine3.18
    needs: [build]
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.5.3
    - name: Installing basic dependencies.
      run: apk add make
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ env.DRAKY_IMAGE_ARTIFACT_NAME }}
        path: dist
    - name: Loading image.
      run: docker load --input $DRAKY_IMAGE_PATH
    - name: Testing core.
      run: make test-functional

  test-lint:
    name: Testing linting.
    runs-on: ubuntu-latest
    container: docker:24.0.2-cli-alpine3.18
    needs: [build]
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.5.3
    - name: Installing basic dependencies.
      run: apk add make
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ env.DRAKY_IMAGE_ARTIFACT_NAME }}
        path: dist
    - name: Loading image.
      run: docker load --input $DRAKY_IMAGE_PATH
    - name: Testing core.
      run: make test-lint
